# -*- coding: utf-8 -*-
"""Non-Linear Regression [Logistic].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aCeJXQphL7NcyDu9pNjDa7T4JThocdZD
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

EDS = pd.read_csv('china_gdp.csv')
EDS.head()

EDS.info()

EDS.describe()

EDS.columns

sns.pairplot(EDS , height=3 , aspect=1.9 )

sns.heatmap(EDS.corr() ,  annot=True)

x= EDS.Year
y= EDS.Value

def LogisticR (x, b0, b1):
    y = 1/(1 + np.exp(-b0*(x-b1)))
    return y
    
def poly (x, b0, b1, b2, b3 , b4 ):
   y = b0 + b1*x + b2*x**2 + b3*x**3 + b3*x**4 
   return y

xdata =x/max(x)
ydata =y/max(y)

from scipy.optimize import curve_fit
popt, pcov = curve_fit(LogisticR, xdata, ydata) 
print(popt)

y_predict =LogisticR(xdata , *popt)
plt.scatter(xdata , ydata)
plt.plot(xdata , y_predict  , color = "r")

